import { ObjectToMap } from ".";

import {
  Affenpinscher,
  AfghanHound,
  AiredaleTerrier,
  Akita,
  AlaskanKleeKai,
  AlaskanMalamute,
  AmericanBulldog,
  AmericanCockerSpaniel,
  AmericanEskimo,
  AmericanHairlessTerrier,
  AmericanLeopardHound,
  AmericanPitBullTerrier,
  AmericanStaffordshireTerrier,
  AmericanWaterSpaniel,
  AnatolianShepherd,
  Aussiedoodle,
  AustralianCattle,
  AustralianKelpie,
  AustralianLabradoodle,
  AustralianShepherd,
  AustralianSilkyTerrier,
  AustralianTerrier,
  AustralianWorkingKelpie,
  Azawakh,
} from "../assets/dogs";

import {
  Basenji,
  Bassador,
  BassetBleuDeGascogne,
  BassetFauveDeBretagne,
  BassetHound,
  Bassugg,
  BavarianMountainHound,
  Beagador,
  Beagle,
  Beaglier,
  BeardedCollie,
  Beauceron,
  BedlingtonTerrier,
  BedlingtonWhippet,
  BelgianGroenendael,
  BelgianLaekenois,
  BelgianMalinois,
  BelgianShepherd,
  BelgianTervuren,
  Bergamasco,
  Bernedoodle,
  BerneseMountain,
  BichonFrise,
  BichonYorkie,
  Bichpoo,
  BiewerTerrier,
  BlackandTanCoonhound,
  BlackRussianTerrier,
  Bloodhound,
  BlueLacy,
  BluetickCoonhound,
  Boerboel,
  Bolognese,
  Borador,
  BorderCollie,
  BorderJack,
  BorderTerrier,
  Bordoodle,
  Borzoi,
  BostonTerrier,
  BouvierDesFlandres,
  Boxador,
  Boxer,
  BraccoItaliano,
  BraqueDAuvergne,
  Briard,
  Brittany,
  Bugg,
  Bullmastiff,
  BullPei,
  BullTerrier,
} from "../assets/dogs";

import {
  CairnTerrier,
  Canaan,
  CanadianEskimo,
  CaneCorsoItaliano,
  CardiganWelshCorgi,
  CatahoulaLeopard,
  CatalanSheepDog,
  CaucasianShepherd,
  Cavachon,
  CavalierKingCharlesSpaniel,
  Cavapom,
  Cavapoo,
  Cavapoochon,
  CavaTzu,
  CeskyTerrier,
  Cheagle,
  ChesapeakeBayRetriever,
  Chihuahua,
  Chinook,
  Chipoo,
  ChiStaffyBull,
  Chiweenie,
  Chorkie,
  ChowChow,
  ChowShepherd,
  Chug,
  Chusky,
  CirnecoDellEtna,
  ClumberSpaniel,
  Cockachon,
  Cockador,
  Cockapoo,
  CockerSpaniel,
  Cojack,
  Corgi,
  CotonDeTulear,
  CurlyCoatedRetriever,
} from "../assets/dogs";

import {
  Dachshund,
  Dalmatian,
  Dameranian,
  DandieDinmontTerrier,
  Deerhound,
  Dobermann,
  DogueDeBordeaux,
  Dorkie,
  Doxiepoo,
  DutchShepherd,
} from "../assets/dogs";

import {
  EnglishBulldog,
  EnglishCoonhound,
  EnglishSetter,
  EnglishToyTerrier,
  EntlebucherMountain,
  EstrelaMountain,
  Eurasier,
} from "../assets/dogs";

import {
  FieldSpaniel,
  FinnishLapphund,
  FinnishSpitz,
  FlatCoatedRetriever,
  Foxhound,
  FoxTerrier,
  FrenchBulldog,
  FrenchBullJack,
  FrenchieStaff,
  FrenchPin,
  Frug,
} from "../assets/dogs";

import {
  GerberianShepsky,
  GermanLonghairedPointer,
  GermanPinscher,
  GermanShepherd,
  GermanShorthairedPointer,
  GermanSpitz,
  GermanWirehairedPointer,
  GiantSchnauzer,
  GlenOfImaalTerrier,
  Goberian,
  Goldendoodle,
  GoldenDox,
  GoldenLabrador,
  GoldenRetriever,
  GoldenShepherd,
  GordonSetter,
  GrandBassetGriffonVendeen,
  GrandBleuDeGascogne,
  GreatDane,
  GreatPyrenees,
  GreekHarehound,
  Greenland,
  Greyhound,
  GriffonBruxellois,
  GriffonFauveDeBretagne,
  GreaterSwissMountain,
} from "../assets/dogs";

import {
  HairlessChineseCrested,
  Hamiltonstovare,
  Harrier,
  Havanese,
  Horgi,
  Hovawart,
  HungarianKuvasz,
  HungarianPuli,
  HungarianPumi,
  HungarianVizsla,
} from "../assets/dogs";

import {
  IbizanHound,
  IcelandicSheepdog,
  IrishDoodle,
  IrishRedWhiteSetter,
  IrishSetter,
  IrishTerrier,
  IrishWaterSpaniel,
  IrishWolfhound,
  ItalianGreyhound,
  ItalianSpinone,
} from "../assets/dogs";

import {
  Jackabee,
  Jackahuahua,
  Jackapoo,
  JackRussellTerrier,
  Jackshund,
  Jacktzu,
  JapaneseAkita,
  JapaneseChin,
  JapaneseShiba,
  JapaneseSpitz,
  JohnsonAmericanBulldog,
  Jug,
} from "../assets/dogs";

import {
  Keeshond,
  KerryBlueTerrier,
  KingCharlesSpaniel,
  Kokoni,
  Komondor,
  Kooikerhondje,
  KoreanJindo,
  KorthalsGriffon,
} from "../assets/dogs";

import {
  LabradorRetriever,
  Labradoodle,
  Lachon,
  LagottoRomagnolo,
  LakelandTerrier,
  LancashireHeeler,
  LargeMunsterlander,
  Leonberger,
  LhasaApso,
  Lhasapoo,
  Lhatese,
  Löwchen,
  Lurcher,
} from "../assets/dogs";

import {
  MalShi,
  Maltese,
  Maltichon,
  Maltipom,
  MaltiPoo,
  ManchesterTerrier,
  MaremmaSheepdog,
  Mastiff,
  MexicanHairless,
  MiniatureBullTerrier,
  MiniaturePinscher,
  MiniaturePoodle,
  MiniatureSchnauzer,
  MiniatureSchnoxie,
  MixedBreed,
  Morkie,
} from "../assets/dogs";

import {
  NeapolitanMastiff,
  Newfoundland,
  NewZealandHuntaway,
  NorfolkTerrier,
  NorthernInuit,
  NorwegianBuhund,
  NorwegianElkhound,
  NorwichTerrier,
  NovaScotiaDuckTollingRetriever,
} from "../assets/dogs";

import { OldEnglishSheepdog, Otterhound } from "../assets/dogs";

import {
  Papillon,
  ParsonRussellTerrier,
  PatterdaleTerrier,
  Peekapoo,
  Pekingese,
  PembrokeWelshCorgi,
  PetitBassetGriffonVendeen,
  PharaohHound,
  PicardySheepdog,
  Pitsky,
  PlottHound,
  Pointer,
  PolishLowlandSheepdog,
  Pomapoo,
  Pomchi,
  Pomeranian,
  Pomsky,
  Poodle,
  PortuguesePodengo,
  PortuguesePointer,
  PortugueseWater,
  PowderpuffChineseCrested,
  Pug,
  Pugalier,
  Pugapoo,
  Puggle,
  Pugzu,
  PyreneanMastiff,
  PyreneanShepherd,
} from "../assets/dogs";

import {
  RatTerrier,
  RedboneCoonhound,
  Rescue,
  RhodesianRidgeback,
  Rottweiler,
  RoughCollie,
  RussianToy,
} from "../assets/dogs";

import {
  Saluki,
  Samoyed,
  Schipperke,
  Schnauzer,
  Schnoodle,
  ScottishTerrier,
  SealyhamTerrier,
  SegugioItaliano,
  SharPei,
  Sheepadoodle,
  ShetlandSheepdog,
  Shihpoo,
  ShihTzu,
  Shollie,
  Shorkie,
  SiberianCocker,
  SiberianHusky,
  Sloughi,
  SlovakianRoughHairedPointer,
  SmallMunsterlander,
  SmoothCollie,
  SoftCoatedWheatenTerrier,
  SpanishWater,
  SportingLucasTerrier,
  Springador,
  SpringerSpaniel,
  Sprocker,
  Sprollie,
  Sproodle,
  Stabyhoun,
  Staffador,
  StaffordshireBullTerrier,
  StaffyJack,
  StBernard,
  SussexSpaniel,
  SwedishLapphund,
  SwedishVallhund,
  SkyeTerrier,
} from "../assets/dogs";

import {
  Tamaskan,
  TerriPoo,
  TibetanMastiff,
  TibetanSpaniel,
  TibetanTerrier,
  ToyFoxTerrier,
  ToyPoodle,
  Trailhound,
  TreeingWalkerCoonhound,
  TurkishKangal,
} from "../assets/dogs";

import {
  Weimaraner,
  WelshSpringerSpaniel,
  WelshTerrier,
  WestHighlandWhiteTerrier,
  Westiepoo,
  Whippet,
  WhiteSwissShepherd,
  WorkingCockerSpaniel,
} from "../assets/dogs";

import { YorkieRussell, Yorkipoo, YorkshireTerrier } from "../assets/dogs";

import { Zuchon } from "../assets/dogs";

const entries = {
  Affenpinscher: Affenpinscher,
  "Afghan Hound": AfghanHound,
  "American Leopard Hound": AmericanLeopardHound,
  "American Pit Bull Terrier": AmericanPitBullTerrier,
  "American Staffordshire Terrier": AmericanStaffordshireTerrier,
  "American Water Spaniel": AmericanWaterSpaniel,
  "Anatolian Shepherd": AnatolianShepherd,
  Aussiedoodle: Aussiedoodle,
  "Australian Cattle": AustralianCattle,
  "Australian Kelpie": AustralianKelpie,
  "Australian Labradoodle": AustralianLabradoodle,
  "Australian Shepherd": AustralianShepherd,
  "Australian Silky Terrier": AustralianSilkyTerrier,
  "Australian Terrier": AustralianTerrier,
  "Australian Working Kelpie": AustralianWorkingKelpie,
  "Airedale Terrier": AiredaleTerrier,
  Akita: Akita,
  "Alaskan Klee Kai": AlaskanKleeKai,
  "Alaskan Malamute": AlaskanMalamute,
  "American Bulldog": AmericanBulldog,
  "American Cocker Spaniel": AmericanCockerSpaniel,
  "American Eskimo": AmericanEskimo,
  "American Hairless Terrier": AmericanHairlessTerrier,
  Azawakh: Azawakh,
  Basenji: Basenji,
  Bassador: Bassador,
  "Basset Bleu De Gascogne": BassetBleuDeGascogne,
  "Basset Fauve De Bretagne": BassetFauveDeBretagne,
  "Basset Hound": BassetHound,
  Bassugg: Bassugg,
  "Bavarian Mountain Hound": BavarianMountainHound,
  Beagador: Beagador,
  Beagle: Beagle,
  Beaglier: Beaglier,
  "Bearded Collie": BeardedCollie,
  Beauceron: Beauceron,
  "Bedlington Terrier": BedlingtonTerrier,
  "Bedlington Whippet": BedlingtonWhippet,
  "Belgian Groenendael": BelgianGroenendael,
  "Belgian Laekenois": BelgianLaekenois,
  "Belgian Malinois": BelgianMalinois,
  "Belgian Shepherd": BelgianShepherd,
  "Belgian Tervuren": BelgianTervuren,
  Bergamasco: Bergamasco,
  Bernedoodle: Bernedoodle,
  "Bernese Mountain": BerneseMountain,
  "Bichon Frise": BichonFrise,
  "Bichon Yorkie": BichonYorkie,
  Bichpoo: Bichpoo,
  "Biewer Terrier": BiewerTerrier,
  "Black and Tan Coonhound": BlackandTanCoonhound,
  "Black Russian Terrier": BlackRussianTerrier,
  Bloodhound: Bloodhound,
  "Blue Lacy": BlueLacy,
  "Bluetick Coonhound": BluetickCoonhound,
  Boerboel: Boerboel,
  Bolognese: Bolognese,
  Borador: Borador,
  "Border Collie": BorderCollie,
  "Border Jack": BorderJack,
  "Border Terrier": BorderTerrier,
  Bordoodle: Bordoodle,
  Borzoi: Borzoi,
  "Boston Terrier": BostonTerrier,
  "Bouvier Des Flandres": BouvierDesFlandres,
  Boxador: Boxador,
  Boxer: Boxer,
  "Bracco Italiano": BraccoItaliano,
  "Braque D' Auvergne": BraqueDAuvergne,
  Briard: Briard,
  Brittany: Brittany,
  Bugg: Bugg,
  Bullmastiff: Bullmastiff,
  "Bull Pei": BullPei,
  "Bull Terrier": BullTerrier,
  "Cairn Terrier": CairnTerrier,
  Canaan: Canaan,
  "Canadian Eskimo": CanadianEskimo,
  "Cane Corso Italiano": CaneCorsoItaliano,
  "Cardigan Welsh Corgi": CardiganWelshCorgi,
  "Catahoula Leopard": CatahoulaLeopard,
  "Catalan Sheep Dog": CatalanSheepDog,
  "Caucasian Shepherd": CaucasianShepherd,
  Cavachon: Cavachon,
  "Cavalier King Charles Spaniel": CavalierKingCharlesSpaniel,
  Cavapom: Cavapom,
  Cavapoo: Cavapoo,
  Cavapoochon: Cavapoochon,
  "Cava Tzu": CavaTzu,
  "Cesky Terrier": CeskyTerrier,
  Cheagle: Cheagle,
  "Chesapeake Bay Retriever": ChesapeakeBayRetriever,
  Chihuahua: Chihuahua,
  Chinook: Chinook,
  Chipoo: Chipoo,
  "ChiStaffy Bull": ChiStaffyBull,
  Chiweenie: Chiweenie,
  Chorkie: Chorkie,
  "Chow Chow": ChowChow,
  "Chow Shepherd": ChowShepherd,
  Chug: Chug,
  Chusky: Chusky,
  "Cirneco Dell Etna": CirnecoDellEtna,
  "Clumber Spaniel": ClumberSpaniel,
  Cockachon: Cockachon,
  Cockador: Cockador,
  Cockapoo: Cockapoo,
  "Cocker Spaniel": CockerSpaniel,
  Cojack: Cojack,
  Corgi: Corgi,
  "Coton De Tulear": CotonDeTulear,
  "Curly Coated Retriever": CurlyCoatedRetriever,
  Dachshund: Dachshund,
  Dalmatian: Dalmatian,
  Dameranian: Dameranian,
  "Dandie Dinmont Terrier": DandieDinmontTerrier,
  Deerhound: Deerhound,
  Dobermann: Dobermann,
  "Dogue de Bordeaux": DogueDeBordeaux,
  Dorkie: Dorkie,
  Doxiepoo: Doxiepoo,
  "Dutch Shepherd": DutchShepherd,
  "English Bulldog": EnglishBulldog,
  "English Coonhound": EnglishCoonhound,
  "English Setter": EnglishSetter,
  "English Toy Terrier": EnglishToyTerrier,
  "Entlebucher Mountain": EntlebucherMountain,
  "Estrela Mountain": EstrelaMountain,
  Eurasier: Eurasier,
  "Field Spaniel": FieldSpaniel,
  "Finnish Lapphund": FinnishLapphund,
  "Finnish Spitz": FinnishSpitz,
  "Flat-Coated Retriever": FlatCoatedRetriever,
  Foxhound: Foxhound,
  "Fox Terrier": FoxTerrier,
  "French Bulldog": FrenchBulldog,
  "French Bull Jack": FrenchBullJack,
  "Frenchie Staff": FrenchieStaff,
  "French Pin": FrenchPin,
  Frug: Frug,
  "Gerberian Shepsky": GerberianShepsky,
  "German Longhaired Pointer": GermanLonghairedPointer,
  "German Pinscher": GermanPinscher,
  "German Shepherd": GermanShepherd,
  "German Shorthaired Pointer": GermanShorthairedPointer,
  "German Spitz": GermanSpitz,
  "German Wirehaired Pointer": GermanWirehairedPointer,
  "Giant Schnauzer": GiantSchnauzer,
  "Glen Of Imaal Terrier": GlenOfImaalTerrier,
  Goberian: Goberian,
  Goldendoodle: Goldendoodle,
  "Golden Dox": GoldenDox,
  "Golden Labrador": GoldenLabrador,
  "Golden Retriever": GoldenRetriever,
  "Golden Shepherd": GoldenShepherd,
  "Gordon Setter": GordonSetter,
  "Grand Basset Griffon Vendeen": GrandBassetGriffonVendeen,
  "Grand Bleu De Gascogne": GrandBleuDeGascogne,
  "Great Dane": GreatDane,
  "Great Pyrenees": GreatPyrenees,
  "Greater Swiss Mountain": GreaterSwissMountain,
  "Greek Harehound": GreekHarehound,
  Greenland: Greenland,
  Greyhound: Greyhound,
  "Griffon Bruxellois": GriffonBruxellois,
  "Griffon Fauve De Bretagne": GriffonFauveDeBretagne,
  "Hairless Chinese Crested": HairlessChineseCrested,
  Hamiltonstovare: Hamiltonstovare,
  Harrier: Harrier,
  Havanese: Havanese,
  Horgi: Horgi,
  Hovawart: Hovawart,
  "Hungarian Kuvasz": HungarianKuvasz,
  "Hungarian Puli": HungarianPuli,
  "Hungarian Pumi": HungarianPumi,
  "Hungarian Vizsla": HungarianVizsla,
  "Ibizan Hound": IbizanHound,
  "Icelandic Sheepdog": IcelandicSheepdog,
  "Irish Doodle": IrishDoodle,
  "Irish Red & White Setter": IrishRedWhiteSetter,
  "Irish Setter": IrishSetter,
  "Irish Terrier": IrishTerrier,
  "Irish Water Spaniel": IrishWaterSpaniel,
  "Irish Wolfhound": IrishWolfhound,
  "Italian Greyhound": ItalianGreyhound,
  "Italian Spinone": ItalianSpinone,
  "Jack-A-Bee": Jackabee,
  Jackahuahua: Jackahuahua,
  "Jack-A-Poo": Jackapoo,
  "Jack Russell Terrier": JackRussellTerrier,
  Jackshund: Jackshund,
  Jacktzu: Jacktzu,
  "Japanese Akita": JapaneseAkita,
  "Japanese Chin": JapaneseChin,
  "Japanese Shiba": JapaneseShiba,
  "Japanese Spitz": JapaneseSpitz,
  "Johnson American Bulldog": JohnsonAmericanBulldog,
  Jug: Jug,
  Keeshond: Keeshond,
  "Kerry Blue Terrier": KerryBlueTerrier,
  "King Charles Spaniel": KingCharlesSpaniel,
  Kokoni: Kokoni,
  Komondor: Komondor,
  Kooikerhondje: Kooikerhondje,
  "Korean Jindo": KoreanJindo,
  "Korthals Griffon": KorthalsGriffon,
  Labradoodle: Labradoodle,
  "Labrador Retriever": LabradorRetriever,
  Lachon: Lachon,
  "Lagotto Romagnolo": LagottoRomagnolo,
  "Lakeland Terrier": LakelandTerrier,
  "Lancashire Heeler": LancashireHeeler,
  "Large Munsterlander": LargeMunsterlander,
  Leonberger: Leonberger,
  "Lhasa Apso": LhasaApso,
  Lhasapoo: Lhasapoo,
  Lhatese: Lhatese,
  Löwchen: Löwchen,
  Lurcher: Lurcher,
  "Mal-Shi": MalShi,
  Maltese: Maltese,
  Maltichon: Maltichon,
  Maltipom: Maltipom,
  "Malti-Poo": MaltiPoo,
  "Manchester Terrier": ManchesterTerrier,
  "Maremma Sheepdog": MaremmaSheepdog,
  Mastiff: Mastiff,
  "Mexican Hairless": MexicanHairless,
  "Miniature Bull Terrier": MiniatureBullTerrier,
  "Miniature Pinscher": MiniaturePinscher,
  "Miniature Poodle": MiniaturePoodle,
  "Miniature Schnauzer": MiniatureSchnauzer,
  "Miniature Schnoxie": MiniatureSchnoxie,
  "Mixed Breed": MixedBreed,
  Morkie: Morkie,
  "Neapolitan Mastiff": NeapolitanMastiff,
  Newfoundland: Newfoundland,
  "New Zealand Huntaway": NewZealandHuntaway,
  "Norfolk Terrier": NorfolkTerrier,
  "Northern Inuit": NorthernInuit,
  "Norwegian Buhund": NorwegianBuhund,
  "Norwegian Elkhound": NorwegianElkhound,
  "Norwich Terrier": NorwichTerrier,
  "Nova Scotia Duck Tolling Retriever": NovaScotiaDuckTollingRetriever,
  "Old English Sheepdog": OldEnglishSheepdog,
  Otterhound: Otterhound,
  Papillon: Papillon,
  "Parson Russell Terrier": ParsonRussellTerrier,
  "Patterdale Terrier": PatterdaleTerrier,
  "Peek-a-poo": Peekapoo,
  Pekingese: Pekingese,
  "Pembroke Welsh Corgi": PembrokeWelshCorgi,
  "Petit Basset Griffon Vendeen": PetitBassetGriffonVendeen,
  "Pharaoh Hound": PharaohHound,
  "Picardy Sheepdog": PicardySheepdog,
  Pitsky: Pitsky,
  "Plott Hound": PlottHound,
  Pointer: Pointer,
  "Polish Lowland Sheepdog": PolishLowlandSheepdog,
  Pomapoo: Pomapoo,
  Pomchi: Pomchi,
  Pomeranian: Pomeranian,
  Pomsky: Pomsky,
  Poodle: Poodle,
  "Portuguese Podengo": PortuguesePodengo,
  "Portuguese Pointer": PortuguesePointer,
  "Portuguese Water": PortugueseWater,
  "Powderpuff Chinese Crested": PowderpuffChineseCrested,
  Pug: Pug,
  Pugalier: Pugalier,
  Pugapoo: Pugapoo,
  Puggle: Puggle,
  Pugzu: Pugzu,
  "Pyrenean Mastiff": PyreneanMastiff,
  "Pyrenean Shepherd": PyreneanShepherd,
  "Rat Terrier": RatTerrier,
  "Redbone Coonhound": RedboneCoonhound,
  Rescue: Rescue,
  "Rhodesian Ridgeback": RhodesianRidgeback,
  Rottweiler: Rottweiler,
  "Rough Collie": RoughCollie,
  "Russian Toy": RussianToy,
  Saluki: Saluki,
  Samoyed: Samoyed,
  Schipperke: Schipperke,
  Schnauzer: Schnauzer,
  Schnoodle: Schnoodle,
  "Scottish Terrier": ScottishTerrier,
  "Sealyham Terrier": SealyhamTerrier,
  "Segugio Italiano": SegugioItaliano,
  "Shar Pei": SharPei,
  Sheepadoodle: Sheepadoodle,
  "Shetland Sheepdog": ShetlandSheepdog,
  "Shih-poo": Shihpoo,
  "Shih Tzu": ShihTzu,
  Shollie: Shollie,
  Shorkie: Shorkie,
  "Siberian Cocker": SiberianCocker,
  "Siberian Husky": SiberianHusky,
  "Skye Terrier": SkyeTerrier,
  Sloughi: Sloughi,
  "Slovakian Rough Haired Pointer": SlovakianRoughHairedPointer,
  "Small Munsterlander": SmallMunsterlander,
  "Smooth Collie": SmoothCollie,
  "Soft Coated Wheaten Terrier": SoftCoatedWheatenTerrier,
  "Spanish Water": SpanishWater,
  "Sporting Lucas Terrier": SportingLucasTerrier,
  Springador: Springador,
  "Springer Spaniel": SpringerSpaniel,
  Sprocker: Sprocker,
  Sprollie: Sprollie,
  Sproodle: Sproodle,
  Stabyhoun: Stabyhoun,
  Staffador: Staffador,
  "Staffordshire Bull Terrier": StaffordshireBullTerrier,
  "Staffy Jack": StaffyJack,
  "St. Bernard": StBernard,
  "Sussex Spaniel": SussexSpaniel,
  "Swedish Lapphund": SwedishLapphund,
  "Swedish Vallhund": SwedishVallhund,
  Tamaskan: Tamaskan,
  "Terri-Poo": TerriPoo,
  "Tibetan Mastiff": TibetanMastiff,
  "Tibetan Spaniel": TibetanSpaniel,
  "Tibetan Terrier": TibetanTerrier,
  "Toy Fox Terrier": ToyFoxTerrier,
  "Toy Poodle": ToyPoodle,
  Trailhound: Trailhound,
  "Treeing Walker Coonhound": TreeingWalkerCoonhound,
  "Turkish Kangal": TurkishKangal,
  Weimaraner: Weimaraner,
  "Welsh Springer Spaniel": WelshSpringerSpaniel,
  "Welsh Terrier": WelshTerrier,
  "West Highland White Terrier": WestHighlandWhiteTerrier,
  Westiepoo: Westiepoo,
  Whippet: Whippet,
  "White Swiss Shepherd": WhiteSwissShepherd,
  "Working Cocker Spaniel": WorkingCockerSpaniel,
  "Yorkie Russell": YorkieRussell,
  Yorkipoo: Yorkipoo,
  "Yorkshire Terrier": YorkshireTerrier,
  Zuchon: Zuchon,
};

const map = ObjectToMap(entries);
const names = Array.from(map.keys());

export default {
  entries,
  names,
  map,
};
