import { Affenpinscher } from "../assets/images/dogs";

const breeds: Array<{ name: string; icon: string } | string> = [
  {
    name: "Affenpinscher",
    icon: Affenpinscher,
  },
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Klee Kai",
  "Alaskan Malamute",
  "American Bulldog",
  "American Cocker Spaniel",
  "American Eskimo",
  "American Hairless Terrier",
  "American Leopard Hound",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "Anatolian Shepherd",
  "Aussiedoodle",
  "Australian Cattle",
  "Australian Kelpie",
  "Australian Labradoodle",
  "Australian Shepherd",
  "Australian Silky Terrier",
  "Australian Terrier",
  "Australian Working Kelpie",
  "Azawakh",
  "Basenji",
  "Bassador",
  "Basset Bleu De Gascogne",
  "Basset Fauve De Bretagne",
  "Basset Hound",
  "Bassugg",
  "Bavarian Mountain Hound",
  "Beagador",
  "Beagle",
  "Beaglier",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Bedlington Whippet",
  "Belgian Groenendael",
  "Belgian Laekenois",
  "Belgian Malinois",
  "Belgian Shepherd",
  "Belgian Tervuren",
  "Bergamasco",
  "Bernedoodle",
  "Bernese Mountain",
  "Bichon Frise",
  "Bichon Yorkie",
  "Bich-poo",
  "Biewer Terrier",
  "Black and Tan Coonhound",
  "Black Russian Terrier",
  "Bloodhound",
  "Blue Lacy",
  "Bluetick Coonhound",
  "Boerboel",
  "Bolognese",
  "Borador",
  "Border Collie",
  "Border Jack",
  "Border Terrier",
  "Bordoodle",
  "Borzoi",
  "Boston Terrier",
  "Bouvier Des Flandres",
  "Boxador",
  "Boxer",
  "Bracco Italiano",
  "Braque D'Auvergne",
  "Briard",
  "Brittany",
  "Bugg",
  "Bullmastiff",
  "Bull Pei",
  "Bull Terrier",
  "Cairn Terrier",
  "Canaan",
  "Canadian Eskimo",
  "Cane Corso Italiano",
  "Cardigan Welsh Corgi",
  "Catahoula Leopard",
  "Catalan Sheepdog",
  "Caucasian Shepherd",
  "Cavachon",
  "Cavalier King Charles Spaniel",
  "Cavapom",
  "Cavapoo",
  "Cavapoochon",
  "Cava Tzu",
  "Cesky Terrier",
  "Cheagle",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinook",
  "Chipoo",
  "Chi Staffy Bull",
  "Chiweenie",
  "Chorkie",
  "Chow Chow",
  "Chow Shepherd",
  "Chug",
  "Chusky",
  "Cirneco Dell'Etna",
  "Clumber Spaniel",
  "Cockachon",
  "Cockador",
  "Cockapoo",
  "Cocker Spaniel",
  "Cojack",
  "Corgi",
  "Coton De Tulear",
  "Curly Coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Dameranian",
  "Dandie Dinmont Terrier",
  "Deerhound",
  "Dobermann",
  "Dogue de Bordeaux",
  "Dorkie",
  "Doxiepoo",
  "Dutch Shepherd",
  "English Bulldog",
  "English Coonhound",
  "English Setter",
  "English Toy Terrier",
  "Entlebucher Mountain",
  "Estrela Mountain",
  "Eurasier",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "Foxhound",
  "Fox Terrier",
  "French Bulldog",
  "French Bull Jack",
  "Frenchie Staff",
  "French Pin",
  "Frug",
  "Gerberian Shepsky",
  "German Longhaired Pointer",
  "German Pinscher",
  "German Shepherd",
  "German Sheprador",
  "German Shorthaired Pointer",
  "German Spitz",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen Of Imaal Terrier",
  "Goberian",
  "Goldendoodle",
  "Golden Dox",
  "Golden Labrador",
  "Golden Retriever",
  "Golden Shepherd",
  "Gordon Setter",
  "Grand Basset Griffon Vendeen",
  "Grand Bleu De Gascogne",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain",
  "Greek Harehound",
  "Greenland",
  "Greyhound",
  "Griffon Bruxellois",
  "Griffon Fauve De Bretagne",
  "Hairless Chinese Crested",
  "Hamiltonstovare",
  "Harrier",
  "Havanese",
  "Horgi",
  "Hovawart",
  "Hungarian Kuvasz",
  "Hungarian Puli",
  "Hungarian Pumi",
  "Hungarian Vizsla",
  "Ibizan Hound",
  "Icelandic Sheepdog",
  "Irish Doodle",
  "Irish Red & White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Italian Spinone",
  "Jack-A-Bee",
  "Jackahuahua",
  "Jack-A-Poo",
  "Jack Russell Terrier",
  "Jackshund",
  "Jacktzu",
  "Japanese Akita",
  "Japanese Chin",
  "Japanese Shiba",
  "Japanese Spitz",
  "Johnson American Bulldog",
  "Jug",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Kokoni",
  "Komondor",
  "Kooikerhondje",
  "Korean Jindo",
  "Korthals Griffon",
  "Labradoodle",
  "Labrador Retriever",
  "Lachon",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Large Munsterlander",
  "Leonberger",
  "Lhasa Apso",
  "Lhasapoo",
  "Lhatese",
  "Löwchen",
  "Lurcher",
  "Mal-Shi",
  "Maltese",
  "Maltichon",
  "Maltipom",
  "Malti-Poo",
  "Manchester Terrier",
  "Maremma Sheepdog",
  "Mastiff",
  "Mexican Hairless",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Poodle",
  "Miniature Schnauzer",
  "Miniature Schnoxie",
  "Mixed Breed",
  "Morkie",
  "Neapolitan Mastiff",
  "Newfoundland",
  "New Zealand Huntaway",
  "Norfolk Terrier",
  "Northern Inuit",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Patterdale Terrier",
  "Peek-a-poo",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Petit Basset Griffon Vendeen",
  "Pharaoh Hound",
  "Picardy Sheepdog",
  "Pitsky",
  "Plott Hound",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Pomapoo",
  "Pomchi",
  "Pomeranian",
  "Pomsky",
  "Poodle",
  "Portuguese Podengo",
  "Portuguese Pointer",
  "Portuguese Water",
  "Powderpuff Chinese Crested",
  "Pug",
  "Pugalier",
  "Pugapoo",
  "Puggle",
  "Pugzu",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rescue",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Rough Collie",
  "Russian Toy",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Schnoodle",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Segugio Italiano",
  "Shar Pei",
  "Sheepadoodle",
  "Shetland Sheepdog",
  "Shih-poo",
  "Shih Tzu",
  "Shollie",
  "Shorkie",
  "Siberian Cocker",
  "Siberian Husky",
  "Skye Terrier",
  "Sloughi",
  "Slovakian Rough Haired Pointer",
  "Small Munsterlander",
  "Smooth Collie",
  "Soft Coated Wheaten Terrier",
  "Spanish Water",
  "Sporting Lucas Terrier",
  "Springador",
  "Springer Spaniel",
  "Sprocker",
  "Sprollie",
  "Sproodle",
  "Stabyhoun",
  "Staffador",
  "Staffordshire Bull Terrier",
  "Staffy Jack",
  "St. Bernard",
  "Sussex Spaniel",
  "Swedish Lapphund",
  "Swedish Vallhund",
  "Tamaskan",
  "Terri-Poo",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Fox Terrier",
  "Toy Poodle",
  "Trailhound",
  "Treeing Walker Coonhound",
  "Turkish Kangal",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Westiepoo",
  "Whippet",
  "White Swiss Shepherd",
  "Working Cocker Spaniel",
  "Yorkie Russell",
  "Yorkipoo",
  "Yorkshire Terrier",
  "Zuchon",
];

export default breeds;
