import { ObjectToMap } from ".";

import {
  Affenpinscher,
  AfghanHound,
  AiredaleTerrier,
  Akita,
  AlaskanKleeKai,
  AlaskanMalamute,
  AmericanBulldog,
  AmericanCockerSpaniel,
  AmericanEskimo,
  AmericanHairlessTerrier,
  AmericanLeopardHound,
  AmericanPitBullTerrier,
  AmericanStaffordshireTerrier,
  AmericanWaterSpaniel,
  AnatolianShepherd,
  Aussiedoodle,
  AustralianCattle,
  AustralianKelpie,
  AustralianLabradoodle,
  AustralianShepherd,
  AustralianSilkyTerrier,
  AustralianTerrier,
  AustralianWorkingKelpie,
  Azawakh,
} from "../assets/dogs";

import {
  Basenji,
  Bassador,
  BassetBleuDeGascogne,
  BassetFauveDeBretagne,
  BassetHound,
  Bassugg,
  BavarianMountainHound,
  Beagador,
  Beagle,
  Beaglier,
  BeardedCollie,
  Beauceron,
  BedlingtonTerrier,
  BedlingtonWhippet,
  BelgianGroenendael,
  BelgianLaekenois,
  BelgianMalinois,
  BelgianShepherd,
  BelgianTervuren,
  Bergamasco,
  Bernedoodle,
  BerneseMountain,
  BichonFrise,
  BichonYorkie,
  Bichpoo,
  BiewerTerrier,
  BlackandTanCoonhound,
  BlackRussianTerrier,
  Bloodhound,
  BlueLacy,
  BluetickCoonhound,
  Boerboel,
  Bolognese,
  Borador,
  BorderCollie,
  BorderJack,
  BorderTerrier,
  Bordoodle,
  Borzoi,
  BostonTerrier,
  BouvierDesFlandres,
  Boxador,
  Boxer,
  BraccoItaliano,
  BraqueDAuvergne,
  Briard,
  Brittany,
  Bugg,
  Bullmastiff,
  BullPei,
  BullTerrier,
} from "../assets/dogs";

import {
  CairnTerrier,
  Canaan,
  CanadianEskimo,
  CaneCorsoItaliano,
  CardiganWelshCorgi,
  CatahoulaLeopard,
  CatalanSheepDog,
  CaucasianShepherd,
  Cavachon,
  CavalierKingCharlesSpaniel,
  Cavapom,
  Cavapoo,
  Cavapoochon,
  CavaTzu,
  CeskyTerrier,
  Cheagle,
  ChesapeakeBayRetriever,
  Chihuahua,
  Chinook,
  Chipoo,
  ChiStaffyBull,
  Chiweenie,
  Chorkie,
  ChowChow,
  ChowShepherd,
  Chug,
  Chusky,
  CirnecoDellEtna,
  ClumberSpaniel,
  Cockachon,
  Cockador,
  Cockapoo,
  CockerSpaniel,
  Cojack,
  Corgi,
  CotonDeTulear,
  CurlyCoatedRetriever,
} from "../assets/dogs";

import {
  Dachshund,
  Dalmatian,
  Dameranian,
  DandieDinmontTerrier,
  Deerhound,
  Dobermann,
  DogueDeBordeaux,
  Dorkie,
  Doxiepoo,
  DutchShepherd,
} from "../assets/dogs";

import {
  EnglishBulldog,
  EnglishCoonhound,
  EnglishSetter,
  EnglishToyTerrier,
  EntlebucherMountain,
  EstrelaMountain,
  Eurasier,
} from "../assets/dogs";

import {
  FieldSpaniel,
  FinnishLapphund,
  FinnishSpitz,
  FlatCoatedRetriever,
  Foxhound,
  FoxTerrier,
  FrenchBulldog,
  FrenchBullJack,
  FrenchieStaff,
  FrenchPin,
  Frug,
} from "../assets/dogs";

import {
  GerberianShepsky,
  GermanLonghairedPointer,
  GermanPinscher,
  GermanShepherd,
  GermanShorthairedPointer,
  GermanSpitz,
  GermanWirehairedPointer,
  GiantSchnauzer,
  GlenOfImaalTerrier,
  Goberian,
  Goldendoodle,
  GoldenDox,
  GoldenLabrador,
  GoldenRetriever,
  GoldenShepherd,
  GordonSetter,
  GrandBassetGriffonVendeen,
  GrandBleuDeGascogne,
  GreatDane,
  GreatPyrenees,
  GreekHarehound,
  Greenland,
  Greyhound,
  GriffonBruxellois,
  GriffonFauveDeBretagne,
  GreaterSwissMountain,
} from "../assets/dogs";

import {
  HairlessChineseCrested,
  Hamiltonstovare,
  Harrier,
  Havanese,
  Horgi,
  Hovawart,
  HungarianKuvasz,
  HungarianPuli,
  HungarianPumi,
  HungarianVizsla,
} from "../assets/dogs";

import {
  IbizanHound,
  IcelandicSheepdog,
  IrishDoodle,
  IrishRedWhiteSetter,
  IrishSetter,
  IrishTerrier,
  IrishWaterSpaniel,
  IrishWolfhound,
  ItalianGreyhound,
  ItalianSpinone,
} from "../assets/dogs";

import {
  Jackabee,
  Jackahuahua,
  Jackapoo,
  JackRussellTerrier,
  Jackshund,
  Jacktzu,
  JapaneseAkita,
  JapaneseChin,
  JapaneseShiba,
  JapaneseSpitz,
  JohnsonAmericanBulldog,
  Jug,
} from "../assets/dogs";

import {
  Keeshond,
  KerryBlueTerrier,
  KingCharlesSpaniel,
  Kokoni,
  Komondor,
  Kooikerhondje,
  KoreanJindo,
  KorthalsGriffon,
} from "../assets/dogs";

import {
  LabradorRetriever,
  Labradoodle,
  Lachon,
  LagottoRomagnolo,
  LakelandTerrier,
  LancashireHeeler,
  LargeMunsterlander,
  Leonberger,
  LhasaApso,
  Lhasapoo,
  Lhatese,
  Löwchen,
  Lurcher,
} from "../assets/dogs";

import {
  MalShi,
  Maltese,
  Maltichon,
  Maltipom,
  MaltiPoo,
  ManchesterTerrier,
  MaremmaSheepdog,
  Mastiff,
  MexicanHairless,
  MiniatureBullTerrier,
  MiniaturePinscher,
  MiniaturePoodle,
  MiniatureSchnauzer,
  MiniatureSchnoxie,
  MixedBreed,
  Morkie,
} from "../assets/dogs";

import {
  NeapolitanMastiff,
  Newfoundland,
  NewZealandHuntaway,
  NorfolkTerrier,
  NorthernInuit,
  NorwegianBuhund,
  NorwegianElkhound,
  NorwichTerrier,
  NovaScotiaDuckTollingRetriever,
} from "../assets/dogs";

import { OldEnglishSheepdog, Otterhound } from "../assets/dogs";

import {
  Papillon,
  ParsonRussellTerrier,
  PatterdaleTerrier,
  Peekapoo,
  Pekingese,
  PembrokeWelshCorgi,
  PetitBassetGriffonVendeen,
  PharaohHound,
  PicardySheepdog,
  Pitsky,
  PlottHound,
  Pointer,
  PolishLowlandSheepdog,
  Pomapoo,
  Pomchi,
  Pomeranian,
  Pomsky,
  Poodle,
  PortuguesePodengo,
  PortuguesePointer,
  PortugueseWater,
  PowderpuffChineseCrested,
  Pug,
  Pugalier,
  Pugapoo,
  Puggle,
  Pugzu,
  PyreneanMastiff,
  PyreneanShepherd,
} from "../assets/dogs";

import {
  RatTerrier,
  RedboneCoonhound,
  Rescue,
  RhodesianRidgeback,
  Rottweiler,
  RoughCollie,
  RussianToy,
} from "../assets/dogs";

import {
  Saluki,
  Samoyed,
  Schipperke,
  Schnauzer,
  Schnoodle,
  ScottishTerrier,
  SealyhamTerrier,
  SegugioItaliano,
  SharPei,
  Sheepadoodle,
  ShetlandSheepdog,
  Shihpoo,
  ShihTzu,
  Shollie,
  Shorkie,
  SiberianCocker,
  SiberianHusky,
  Sloughi,
  SlovakianRoughHairedPointer,
  SmallMunsterlander,
  SmoothCollie,
  SoftCoatedWheatenTerrier,
  SpanishWater,
  SportingLucasTerrier,
  Springador,
  SpringerSpaniel,
  Sprocker,
  Sprollie,
  Sproodle,
  Stabyhoun,
  Staffador,
  StaffordshireBullTerrier,
  StaffyJack,
  StBernard,
  SussexSpaniel,
  SwedishLapphund,
  SwedishVallhund,
  SkyeTerrier,
} from "../assets/dogs";

import {
  Tamaskan,
  TerriPoo,
  TibetanMastiff,
  TibetanSpaniel,
  TibetanTerrier,
  ToyFoxTerrier,
  ToyPoodle,
  Trailhound,
  TreeingWalkerCoonhound,
  TurkishKangal,
} from "../assets/dogs";

import {
  Weimaraner,
  WelshSpringerSpaniel,
  WelshTerrier,
  WestHighlandWhiteTerrier,
  Westiepoo,
  Whippet,
  WhiteSwissShepherd,
  WorkingCockerSpaniel,
} from "../assets/dogs";

import { YorkieRussell, Yorkipoo, YorkshireTerrier } from "../assets/dogs";

import { Zuchon } from "../assets/dogs";

const breeds = {
  Affenpinscher: Affenpinscher,
  "Afghan Hound": AfghanHound,
};

const map = ObjectToMap(breeds);
const names = map.keys();

export { names, map };
export default breeds;
